[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ForneyLab = "9fc3f58a-c2cc-5bff-9419-6a294fefdca9"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Documenter = "0.25"
